# Global
global:
  cluster: "https://kubernetes.default.svc"
  repoURL: file://Users/sebastianvaldez/personal_code/gitops-cluster-bootstrap

  kube-vip:
    enabled: true
    image_tag: v0.8.4
    cp_enable: "'true'"
    vip_address: 10.15.50.90
    vip_interface: "eth0"
    vip_leaderelection: "'true'"
    vip_leaseduration: "'5'"
    vip_renewdeadline: "'3'"
    vip_retryperiod: "'1'"

# Still tuning below:
  cert-manager:
    enabled: true

  traefik:
    enabled: true
    targetRevision: v22.0.0

  pihole:
    enabled: false
    vip_address: 10.15.50.91 # exposed via kube-vip and svc loadbalancer
  unboundDns:
    enabled: false
    vip_address: 10.15.50.92 # exposed via kube-vip and svc loadbalancer

  prometheus:
    enabled: false
  grafana:
    enabled: false
  authentik:
    enabled: false
  vault:
    enabled: false
