# Global
global:
  cluster: "https://kubernetes.default.svc"
  repoURL: file://Users/sebastianvaldez/personal_code/gitops-cluster-bootstrap

  kube-vip:
    enabled: true
    image_tag: v0.8.4
    cp_enable: "'true'"
    vip_address: 10.15.50.90
    vip_interface: "eth0"
    vip_leaderelection: "'true'"
    vip_leaseduration: "'5'"
    vip_renewdeadline: "'3'"
    vip_retryperiod: "'1'"

  kube-vip-cloud-provider:
    enabled: true
    cm:
      data:
        cidr-infra: "10.15.50.93/24"

# Still tuning below:
  cert-manager:
    enabled: true

  traefik:
    enabled: true
    targetRevision: v22.0.0
    # vip_address: 10.15.50.91 I

  externalDNS:
    enabled: false
    # used to dynamically manage dns records for k8s services

  istio:
    enabled: false
    # TBD

  pihole:
    enabled: false
    # TBD expose this IP or not.
    vip_address: 10.15.50.92 # exposed via kube-vip and svc loadbalancer
  unboundDns:
    enabled: false
    vip_address: 10.15.50.93 # exposed via kube-vip and svc loadbalancer

  prometheus:
    enabled: false
    # Use this for log collection
  grafana:
    enabled: false
    # Use this for service & cluster health viz
  authentik:
    enabled: false
    # Use this for OIDC for Argo / all other applications.
  vault:
    enabled: false
    # Use this for secret management
  homeAssistant:
    enabled: false
    # Use this for home automation
