# Global
global:
  repoURL: file://Users/sebastianvaldez/personal_code/gitops-cluster-bootstrap

  kube-vip:
    enabled: true
    image_tag: v0.8.4
    cp_enable: "'true'"
    vip_address: 10.15.50.90
    vip_interface: "eth0"
    vip_leaderelection: "'true'"
    vip_leaseduration: "'5'"
    vip_renewdeadline: "'3'"
    vip_retryperiod: "'1'"

  cert-manager:
    enabled: false
  traefik:
    enabled: false


