apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-vip
  source:
    repoURL: 'https://kube-vip.github.io/helm-charts/'
    targetRevision: v0.6.1
    namespace: kube-system
  values:
    configuration:
      vip: "10.15.1.90"        # Define your VIP here
      interface: "eth0"        # Specify the network interface
      gateway: "10.15.1.1"     # Define the gateway
      arp: true
      leaderElection: true
    rbac:
      create: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
