apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: v22.0.0
    namespace: traefik
  values:
  syncPolicy:
    automated: {}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
