{{- if .Values.global.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: {{ index .Values "global" "traefik" "targetRevision" }}
    chart: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end}}
