apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  source:
    repoURL: 'https://kube-vip.github.io/helm-charts'
    targetRevision: v0.6.1
    chart: kube-vip
    helm:
      parameters:
        - name: rbac.create
          value: "true"
        - name: daemonset.enabled
          value: "true"
        - name: configuration.vip
          value: "10.15.1.90"
        - name: configuration.interface
          value: "eth0"
        - name: configuration.arp
          value: "true"
        - name: configuration.controlplane
          value: "true"
        - name: configuration.services.enabled
          value: "false"
        - name: configuration.prometheus.enabled
          value: "false"
        # - name: image.repository
        #   value: "ghcr.io/kube-vip/kube-vip"
        # - name: image.tag
        #   value: "v0.8.5"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true