apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system  # Set to 'kube-system' instead of 'kube-vip' for consistency
  source:
    repoURL: 'https://kube-vip.github.io/helm-charts'
    targetRevision: v0.6.1
    chart: kube-vip
  values:
    daemonset:
      enabled: false    # Disable the default DaemonSet if it exists
    deployment:
      enabled: false    # Disable the default Deployment if it exists
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true