apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  source:
    repoURL: 'https://kube-vip.github.io/helm-charts'
    targetRevision: v0.6.1
    chart: kube-vip
    helm:
      parameters:
        - name: extraArgs.controlplane
          value: "true"
        - name: extraArgs.inCluster
          value: "true"
        - name: extraArgs.taint
          value: "true"
        - name: extraArgs.address
          value: "10.15.1.90"
        - name: extraArgs.interface
          value: "eth0"
        - name: extraArgs.gateway
          value: "10.15.1.1"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
