{{- if index .Values "global" "kube-vip" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: kube-vip
    server: {{ .Values.global.cluster }}
  source:
    repoURL: https://github.com/kube-vip/helm-charts
    targetRevision: kube-vip-0.8.4
    path: charts/kube-vip
    helm:
      parameters:
        - name: config.address
          value: {{ index .Values "global" "kube-vip" "vip_address" }}
        - name: env.vip_interface
          value: {{ index .Values "global" "kube-vip" "vip_interface" }}
        - name: env.vip_leaderelection
          value: {{ index .Values "global" "kube-vip" "vip_leaderelection" }}
        - name: env.cp_enable
          value: {{ index .Values "global" "kube-vip" "cp_enable" }}
        - name: config.vip_leaseduration
          value: {{ index .Values "global" "kube-vip" "vip_leaseduration" }}
        - name: config.vip_renewdeadline
          value: {{ index .Values "global" "kube-vip" "vip_renewdeadline" }}
        - name: config.vip_retryperiod
          value: {{ index .Values "global" "kube-vip" "vip_retryperiod" }}
        - name: image.tag
          value: {{ index .Values "global" "kube-vip" "image_tag" }}
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
