apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
spec:
  destination:
    name: ''
    namespace: kube-vip
    server: https://kubernetes.default.svc
  source:
    path: charts/kube-vip
    repoURL: https://github.com/kube-vip/helm-charts
    targetRevision: kube-vip-0.8.4
    helm:
      parameters:
        - name: config.address
          value: 10.15.50.100
        - name: env.cp_enable
          value: 'true'
        - name: env.vip_leaderelection
          value: 'true'
        - name: env.vip_interface
          value: eth0
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
