apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: kube-vip
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kube-vip
    server: https://kubernetes.default.svc
  source:
    path: charts/kube-vip
    repoURL: https://github.com/kube-vip/helm-charts
    targetRevision: kube-vip-0.8.4
    helm:
      parameters:
        - name: config.address
          value: 10.15.50.90
        - name: env.vip_interface
          value: eth0
        - name: env.vip_leaderelection
          value: 'true'
        - name: env.cp_enable
          value: 'true'
        - name: config.vip_leaseduration
          value: '5'
        - name: config.vip_renewdeadline
          value: '3'
        - name: config.vip_retryperiod
          value: '1'
        - name: image.tag
          value: v0.8.4
        - name: serviceAccount.name
          value: kube-vip
  sources: []
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
